### ISSUE TITLE
Able to jump into root based test folder ?

### ISSUE THREAD

**Issue by DavidBabel** [acino/jump-source#6]
I have this setup : 
![image](https://user-images.githubusercontent.com/5599375/126675218-b09aeff6-997d-4060-a31d-c035ab716e54.png)

Is the extension able to manage that ?

**Comment by peter-spegel** [comment]
I don't think it's possible at the moment, but we will definitively look into it.

**Comment by peter-spegel** [comment]
@DavidBabel This should work in the latest version (1.4.4):
```
{
  "jumpSource.testSubFolder": "",
  "jumpSource.relativeRoots": ["src", "test/src"],
  "jumpSource.testFileSuffix": "spec"
}
```

Happy coding!
